# Site settings
title: Technically Speaking
email: ryin@velomatrix.com
description: > # this means to ignore newlines until "baseurl:"
  We have saved countless hours of frustration by finding solutions to our technology problems and annoyances. It's time to give back to the community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://velomatrix.net" # the base hostname & protocol for your site
twitter_username: rathyin
github_username:  ryin

# Build settings
markdown: kramdown

exclude: [vendor]
